--- #installation of jenkins
- hosts: MinIO_storage
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Download Minio-Cluster docker-compose file
    get_url:
      url: https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
      dest: /tmp
  - name: Pull docker-compose images
    command: cd /tmp && docker-compose pull
  - name: Creating the containers
    command: cd /tmp && docker-compose up -d
  - name: Pull MinIO client
    command: docker pull minio/mc
  - name: Creating the container - MinIO client
    command: docker run minio/mc ls play
  - name: Adding Minio client config
    command: mc config host add minio *use ip from host file* minio minio123
  - name: Adding Minio Bucket named pipe
    command: mc mb minio/pipe
  - name: Creating 1000-1Kb files 
    file:
      state: touch
      path: /tmp/{{ item }}
    loop: "{{ query('sequence', 'start=1 end=1000' }}" 
  - name: Uploading files to Minio
    file:
      state: mc cp
      path: /tmp/{{ item }}
    loop: "{{ query('sequence', 'start=1 end=1000' }}" 
  